# Generated by Django 3.2.16 on 2025-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250320_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Определяет, будет ли категория отображаться.', verbose_name='Видимость'),
        ),
    ]
